name: AppScan CodeSweep

on:
  push:
    branches: [ main ]     # Change to your branch name if different
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ensures full history for accurate diff scanning

      - name: Print event type (for debugging)
        run: 'echo "Triggered by event: ${{ github.event_name }}"'

      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}   # fixes 'null event' issue
          INPUT_SCAN_BASE_NAME: "Python Code Scan"
